services:
  app:
    build: .
    image: kafka-django
    command: sh -c "chmod +x /KafkaDjango/migrate.sh && sh /KafkaDjango/migrate.sh && sh /KafkaDjango/docker-entrypoint.sh"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      pgdb:
        condition: service_healthy
      zookeeper:
        condition: service_started
      kafka:
        condition: service_started
      pgadmin:
        condition: service_started
    volumes:
      - .:/KafkaDjango
    # networks:
    #   - customnetwork

  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"
    # networks:
    #   - customnetwork
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    expose:
      - 9092
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      # KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      # KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      # KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # networks:
    #   - customnetwork
  pgdb:
    image: postgres
    container_name: postgress_djkafka
    # restart: always
    expose:
      - 5432
    ports:
      - "5432:5432"
    # environment:
    #   POSTGRES_USER: pgadmin-user
    #   POSTGRES_PASSWORD: pgadmin
    #   POSTGRES_DB: dockerdatabase
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pgadmin-user -d dockerdatabase"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    # networks:
    #   - customnetwork
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_django
    # restart: always
    ports:
      - "8888:80"
    # environment:
    #   PGADMIN_DEFAULT_EMAIL: redowan@mercegrower.com.com
    #   PGADMIN_DEFAULT_PASSWORD: pgadmin
    env_file:
      - .env
    depends_on:
      - pgdb
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:

# networks:
#   customnetwork: